### ISSUE TITLE
everblog-contrib-gravatar ?

### ISSUE THREAD

**Issue by zhuangya** [everblogjs/everblog#1]
我打算来做一个 `everblog-contrib-gravatar` 好让 theme 作者或者用户选择是不是直接启用 gravatar 上的头像。

但是 everblog 的 plugins 叫做 `everblog-contrib-*` 科学不科学呢？

各位有没有更好的想法呀

**Comment by nswbmw** [comment]
其实可以在 `everblog-adaptor-*` 做吧，我觉得没必要给 theme 的作者选择的权利，应该给 adaptor 的作者更多的权利。应该是 adaptor 提供了可以根据邮箱地址生成 gravatar，那么 theme 才可以用，否则只能用 `_config.yml` 配置里写死的，不过事实是 theme 也可以对传入的数据做改动，在 theme 的 `index.js` 。综上所述：在 adaptor 和 theme 都可以做，就没必要写 plugin 了。。ps: plugin 我更倾向于 `everblog-plugin-*`..

**Comment by zhuangya** [comment]
<del>这个事情，看起来要在 utils 里面加上执行 plugin 的支持 </del>

let me have a deep look

hmm

**Comment by zhuangya** [comment]
https://github.com/zhuangya/everblog-plugin-gravatar

写了一个这个，来处理这个事情。
先在这里写一个简单的用法吧：

在 adaptor 中，拿到 `data` 之后 

``` js

gravatarPlugin(data, gravatarOptions)
```

就好了。。

`gravatorOptions` 具体看[这里](https://github.com/zhuangya/ya-gravatar)
