### ISSUE TITLE
authenticationToken

### ISSUE THREAD

**Issue by o3o3o** [everblogjs/everblog#3]
Hi, when I execute : 

> DEBUG=\* everblog build

here is error:

```
everblog getNotebook -> myblog +0ms                                                            
everblog findNotes -> 1 +44ms

 EDAMSystemException: authenticationToken
```

I assure the yinxiang's dev_token is correct in ~/.everblogrc.
 What I can do? Thank you.

**Comment by zhougy0717** [comment]
This is because the token you are using doesn't match with the serviceHost. For example, if you are using a token of yinxiang user, but you don't specify the serviceHost in your everblogrc. That's a mismatch. And you will definitely get a exception as this one.
