### ISSUE TITLE
Evernote Developer mode has been closed

### ISSUE THREAD

**Issue by kslr** [everblogjs/everblog#7]
Update: the creation of developer tokens is temporarily disabled.

ref https://github.com/suziwen/markdownxiaoshujiang/issues/532

**Comment by bucketzxm** [comment]
@kslr 你可以发邮件给Support帮你开一下

**Comment by kslr** [comment]
@bucketzxm
 但这显然不是一个长久的做法，也不可能要求所有用户做这么多，所以不考虑适配OAuth2吗？

**Comment by nswbmw** [comment]
后续会加上的

**Comment by kslr** [comment]
flag以立

**Comment by nswbmw** [comment]
😵
