### ISSUE TITLE
 ~/.everblogrc must include:

### ISSUE THREAD

**Issue by Rmice** [everblogjs/everblog#9]
$ DEBUG=* everblog start

  ~/.everblogrc must include:

    token: "xxx"
    noteStoreUrl: "xxx"
    notebook: "xxx"
————————————————
你好，可以确定这个文件下是有这三个的，而且如果token；noteSoreUrl；notebook这三个字符写错后会报其他的错。
希望您有时间的时候能帮忙看一下。

**Comment by Rmice** [comment]
好吧，解决了。打扰了。

**Comment by iT-Boyer** [comment]
出现同样的问题
```
token:"S=xxx:U=xxx:E=xxx:C=xxx:P=1cd:A=en-devtoken:V=2:H=xxx",
noteStoreUrl:"https://app.yinxiang.com/shard/xxx/notestore",
notebook:"myblog"
```
是什么原因？
